// Code generated by "stringer -type=Status -linecomment"; DO NOT EDIT.

package haelu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusGood-0]
	_ = x[StatusWarn-1]
	_ = x[StatusBad-2]
}

const _Status_name = "goodwarnbad"

var _Status_index = [...]uint8{0, 4, 8, 11}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
